// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.

$(document).ready(function () {
	
	// top菜单伸缩
	$(".tel-menu").click(function () {
		$(".topmenu-right").toggleClass("bt-menu-open");
		$(this).siblings().removeClass("bt-menu-open");
	});
	
	$(".nav-item2").mouseover(function () {
		$(".topmenu").addClass("menubg-open");
	});
	$(".nav-item2").mouseout(function () {
		$(".topmenu").removeClass("menubg-open");
	});
	
	//滚动条
	
	
	
	//焦点图
	var swiper = new Swiper('.swiper-pc', {
      slidesPerView: 1,
      spaceBetween: 0,
		speed:3500,
		loop:true,
      	autoplay: {
        delay: 6000,
			disableOnInteraction: false,
      	},
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
	var swiper = new Swiper('.swiper-tel', {
      slidesPerView: 1,
      spaceBetween: 0,
		speed:3500,
		loop:true,
      	autoplay: {
        delay: 6000,
			disableOnInteraction: false,
      	},
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
	//产品广告
	var swiper = new Swiper('.swiper-product', {
      slidesPerView: 1,
      spaceBetween: 0,
		speed:1500,
		effect: 'fade',
		loop:true,
      	autoplay: {
        delay: 3000,
			disableOnInteraction: false,
      	},
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
	//团队
	var swiper = new Swiper('.swiper-tuandui', {
		slidesPerView:5,
      spaceBetween:10,
		speed:800,
		pagination: {
        el: '.swiper-pagination',
       clickable: true,
      },
	});
	var swiper = new Swiper('.swiper-tuandui2', {
		slidesPerView:2,
      spaceBetween: 10,
		speed:800,
		loop:true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
	});
	
	//照片
	var swiper = new Swiper('.swiper-pic', {
		slidesPerView:4,
      spaceBetween:10,
		speed:800,
		autoplay: {
        delay: 3000,
			disableOnInteraction: false,
      	},
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
	});
	var swiper = new Swiper('.swiper-pic2', {
		slidesPerView:2,
      spaceBetween: 10,
		speed:800,
		loop:true,
      autoplay: {
        delay: 3000,
			disableOnInteraction: false,
      	},
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
	});
	
});


